### ISSUE TITLE
Tenant Config missing in onboarding guide

### ISSUE THREAD

**Issue by HatariOS** [awslabs/aws-saas-boost#199] opened 2022-02-23 15:32 UTC
---

This is a 📕 documentation issue

**Comment by PoeppingT** [comment] 2022-02-24 18:34
Hi @HatariOS, thanks for the documentation issue report! Can you add more context to this issue to clarify exactly what you mean by tenant config? What documentation file are you expecting this information to be in?

**Comment by brtrvn** [comment] 2022-11-24 00:30
Duplicate of #172

**Closed by brtrvn** 2022-11-24 00:30 UTC
Labels: documentation, priority-low
