### ISSUE TITLE
stuck in Cloudformtion [title] 

### ISSUE THREAD

**Issue by pnjegan** [awslabs/aws-saas-boost#178] opened 2022-01-11 17:05 UTC
### Environment

  - **AWS SaaS Boost Version:**

**Comment by PoeppingT** [comment] 2022-01-11 23:40
Hi @pnjegan , thanks for opening this issue request! Can you provide more information about your issue? In particular:
1. What steps did you try? What did you expect to happen, and what happened instead?
2. Which CloudFormation stack are you stuck in? Is this when creating the SaaS Boost environment, onboarding a tenant, or something else?

Thanks for your participation and with your help we can work to resolve your issue as quickly as possible.

**Comment by pnjegan** [comment] 2022-01-12 13:49
@PoeppingT , it stuck at this stage

2022-01-11 16:29:39.258  INFO  SaaSBoostInstall - [INFO] Total time: 25.676 s
2022-01-11 16:29:39.260  INFO  SaaSBoostInstall - [INFO] Finished at: 2022-01-11T16:29:39Z
2022-01-11 16:29:39.440  INFO  SaaSBoostInstall - [INFO] Final Memory: 55M/190M
2022-01-11 16:29:39.440  INFO  SaaSBoostInstall - [INFO] ------------------------------------------------------------------------
2022-01-11 16:29:39.484  INFO  SaaSBoostInstall - Uploading Lambda source package to S3 metering-billing/lambdas/target/BillingService-lambda.zip -> lambdas/BillingService-lambda.zip
2022-01-11 16:29:39.484  DEBUG SaaSBoostArtifactsBucket - Putting metering-billing/lambdas/target/BillingService-lambda.zip to Artifacts bucket: sb-test-artifacts-9581b529-db40
2022-01-11 16:29:39.677  INFO  SaaSBoostInstall - Running CloudFormation
2022-01-11 16:29:39.684  INFO  SaaSBoostInstall - createSaaSBoostStack::create stack sb-test
2022-01-11 16:29:40.177  INFO  SaaSBoostInstall - createSaaSBoostStack::stack id arn:aws:cloudformation:us-east-1:310864222925:stack/sb-test/ac7b6b10-72fb-11ec-a5e3-0e8a3c442c39

**Comment by aquibchiniwala** [comment] 2022-01-12 15:07
@pnjegan 
There is an issue running the java project on windows os.
After building the lambda functions, on windows, it places on a path separated with "\" forward slash.
While in the cloud formation template the resources search for lambda zip files with path separator "/"

So for time being do a workaround by replacing

!Sub ${LambdaSourceFolder}/

with !Sub ${LambdaSourceFolder}\

for all the files in aws-saas-boost/resources.

But for a permanent fix maybe @PoeppingT would find a way to make file separators uniform on various OS.

**Comment by pnjegan** [comment] 2022-01-12 16:45
@aquibchiniwala , am using Amazon Linux 2 as mentioned in readme.

**Comment by aquibchiniwala** [comment] 2022-01-12 18:41
Still you can try the same approach @pnjegan

**Comment by PoeppingT** [comment] 2022-01-12 18:44
@pnjegan are you following the instructions in [`getting-started.md`](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md)? What steps did you follow to see the stuck script that you saw? CloudFormation `createStack` can take a while to complete, how long was it stuck?

**Comment by pnjegan** [comment] 2022-01-12 19:23
@PoeppingT , Stuck in Step 3 after running install.sh!

**Comment by brtrvn** [comment] 2022-01-12 19:43
Log into the AWS Console and go to CloudFormation and look at the Events and Resources tab for the stack named `sb-test` to see if there are any errors.

If the stack `sb-test` is not visible, change the dropdown near the stack name filter input from Active to Failed.

You can also use the AWS CLI
`aws cloudformation describe-stacks --stack-name arn:aws:cloudformation:us-east-1:310864222925:stack/sb-test/ac7b6b10-72fb-11ec-a5e3-0e8a3c442c39`

**Comment by pnjegan** [comment] 2022-01-12 19:51
![image](https://user-images.githubusercontent.com/28691937/149211592-0899fcfa-8c3f-4997-8446-eead377567fc.png)

**Comment by pnjegan** [comment] 2022-01-13 13:12
@PoeppingT , LMK if any details needed!

**Comment by PoeppingT** [comment] 2022-01-13 17:29
Hi @pnjegan, on that same CloudFormation page you posted a picture for, if you scroll down on that `Events` page you should find an event like `CREATE_FAILED`, which will be tied to a specific resource and should include an error code. That will give you more information into what went wrong, and provide a pathway to fix.

With the information you have provided so far we have no way to reproduce this issue, and so no way to investigate ourselves. You say that you were running Step 3 in `install.sh`. Can you be more explicit: were you installing a new SaaS Boost environment? If so, which options did you select as part of `install.sh`? Were you using the sample java application as recommended in [`getting-started.md`](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md)?

By the way, there are new commits in the repo since yesterday which have fixed a few bugs others have raised reports on. Please try again with the latest version of the `main` branch and provide further information if that fails.

**Comment by pnjegan** [comment] 2022-01-13 18:53
@PoeppingT ,sure, let me try with the repo and update

**Comment by pnjegan** [comment] 2022-01-13 18:54
FYI- Event failed was 

Embedded stack arn:aws:cloudformation:us-east-1:310864222925:stack/sb-test-network-PNE7SZKR9Q9O/b1dd7080-72fb-11ec-98aa-12b6e64cdc09 was not successfully created: The following resource(s) failed to create: [InternetGateway, EgressVPC].

I created new VPC to be used for Cloud9

**Comment by brtrvn** [comment] 2022-01-13 23:43
What was the underlying cause? Did you run out of VPCs? Check your number of VPCs and your service quota. Installing SaaS Boost will require you to have a free VPC slot available in your account and onboarding tenants will require additional VPCs. You will have to increase your VPC quota from the default 5 if you want to onboard more than a couple of tenants.

Go to the **VPC** console and view your list of current VPCs. If it is 5 and you haven't requested a quota increase, you won't be able to install SaaS Boost.

Go to the **Service Quotas** console and choose **Amazon Virtual Private Cloud (Amazon VPC)** from the dashboard. Scroll to the bottom of the list to find the current setting for the VPCs per Region quota. By default, both numbers will be 5. To increase your quota, click on the **Request quota increase** button and fill out the form.

**Comment by PoeppingT** [comment] 2022-01-18 18:44
@pnjegan SaaS Boost does not require a VPC with a private subnet. Have you looked into the comment above from @brtrvn ? The most common issue we see is running into VPC quota limits. Without knowing the actual errors CloudFormation gave you it will be difficult to provide useful help.

**Comment by pnjegan** [comment] 2022-01-18 18:58
No VPC Quota issues ! error i got last week was - The following resource(s) failed to create: [InternetGateway, EgressVPC].

I may run with the latest code tomorrow and update if the same issue occurs

**Comment by PoeppingT** [comment] 2022-01-18 19:29
CloudFormation will give you a reason that those resources failed to create. For example, if a stack failed to create because two subsequent resources failed to create (as you mention) you can navigate into that stack in CloudFormation and look at the same resources tab to find those resources in particular. Thinking of it like asking "I see that the InternetGateway failed to create, but why?" If you can find the InternetGateway resource that failed to create, CloudFormation should tell you exactly why, to help you debug further.

**Comment by PoeppingT** [comment] 2022-04-18 18:53
Hey @pnjegan , it has now been three months without comment on this issue, and we are in the process of releasing v2 of SaaS Boost. If you have no other comments on this issue, I will close it within the week.

**Closed** 2022-04-26 22:54 UTC
Labels: needs-reproduction, question
