### ISSUE TITLE
[IAM policy missing EFS Tagresource action] 

### ISSUE THREAD

**Issue by lhtan-dev** [awslabs/aws-saas-boost#516] opened 2023-05-19 04:39 UTC
### Description of the bug:
Onboarding of tenant fails due to insufficient permission on IAM policy <....OnboardingServiceStorageProvisionPolicy...>. Missing elasticfilesystem:TagResource action.

### Reproduction Steps : 
Perform steps to onboard new tenant.

### What did you expect to happen? : 
Onboarding of tenant to be successful.

### Error Details : 
..is not authorized to perform: elasticfilesystem:TagResource on the specified resource (Service: Efs, Status Code: 403,... ,HandlerErrorCode:GeneralServiceException)...

### Environment

  - **AWS Region  :*ap-southeast-1*
  - **AWS SaaS Boost Version :*Version v2.2.0-15@5ab937b*
  - **Workload OS  (Linux or Windows) :*Linux* SampleApp

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment] 2023-05-19 22:20
Duplicate of #512

**Closed by brtrvn** 2023-05-19 22:20 UTC
Labels: bug, triage
