### ISSUE TITLE
"Application" from the navigation on the left side can't be open

### ISSUE THREAD

**Issue by daniel-hutao** [awslabs/aws-saas-boost#492] opened 2023-03-03 01:26 UTC
The Application tab can't be shown after click.

![image](https://user-images.githubusercontent.com/18692628/222607536-87e05dc7-76da-4911-8608-cf1fb11b4a42.png)

And the safari console show the errors like below:

![image](https://user-images.githubusercontent.com/18692628/222607343-9120fab9-c6b0-4980-9c33-f486b96a6ec5.png)

### Reproduction Steps

All steps I've done are [AWS SaaS Boost Getting Started Guide](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md) - step 1-4; And I failed in step 5 - "Select Application from the navigation on the left side of the screen". I can't open the Application from the navigation.

### What did you expect to happen?

Application page

### What actually happened?

A white page will be return after click.

### Environment

  - **AWS Region  :*us-east-1*
  - **AWS SaaS Boost Version :*latest version(Mar 2, 2023)*
  - **Workload OS  (Linux or Windows) :*Linux*

### Other

--- 

This is :bug: Bug Report

**Comment by daniel-hutao** [comment] 2023-03-03 03:04
v2.2.0 is the same.

**Comment by PoeppingT** [comment] 2023-03-07 17:58
Hi @daniel-hutao , I am not able to reproduce this with my environment. Please provide the following information:
1. can you still reproduce this issue?
2. which web browser + version are you using?
3. the Admin Web UI is built using CodeBuild in your AWS account in the job titled `sb-${environment}-admin-web` (in your case, since the environment is named `test`, the CodeBuild project will be named `sb-test-admin-web`). Are there any errors with that Build job?
4. if you delete your test environment and create a new one, does the issue persist?

**Comment by daniel-hutao** [comment] 2023-03-09 07:04
@PoeppingT Hi, I struggled with this problem for a few days, but eventually gave up. I have deleted my environment already.

I have tried several times, so it's obvious that this problem is not sporadic. Moreover, I have found the error message in the console, which is a JavaScript error as I posted earlier. I believe that this error is definitely not related to the browser version, but I am still happy to provide my browser information, which is Safari Version 16.2 (18614.3.7.1.5).

I was planning to deploy my SaaS on AWS, but due to this failed experience, I have given up on the *AWS SaaS Boost* solution. I am concerned that similar "blocking issues" may occur frequently in the future, and they may not be resolved quickly. Such issues could be fatal once our product is officially on the AWS.

**Comment by brtrvn** [comment] 2023-04-04 17:18
From that error in the JavaScript console, it appears that the React project build did not complete successfully and transfer the files to S3 where they are hosted from. Debugging would best be done by looking at the CodeBuild project logs to see if there were any issues.

Closing this issue as the original reporter seems to have moved on, but feel free to reopen if anyone can reproduce this.

**Closed by brtrvn** 2023-04-04 17:18 UTC
Labels: bug, needs-reproduction, admin-ui
