### ISSUE TITLE
Admin UI User Detail page "Created On" shows current time

### ISSUE THREAD

**Issue by PoeppingT** [awslabs/aws-saas-boost#176] opened 2022-01-10 21:50 UTC
In the Admin UI User Detail page (Users on the sidebar -> click on a user) the "created on" information appears to always be the current time.

### Reproduction Steps

1. In an existing or new SaaS Boost environment, sign in to the Admin UI
2. Go to the Users list from the left sidebar
3. Click on any user
4. Note that the "Created On" time appears to be the current time

### What did you expect to happen?

The "Created On" time should represent the time the user was created in the Cognito UserPool

### What actually happened?

The "Created On" time appears to be the current time

### Environment

  - **AWS Region  :** us-west-2
  - **AWS SaaS Boost Version :** v1.1
  - **Workload OS  (Linux or Windows) :** Linux

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment] 2022-01-13 23:16
Duplicate of #84 
Add to the list of validations

**Comment by brtrvn** [comment] 2022-11-24 00:38
Resolved with #428

**Closed by brtrvn** 2022-11-24 00:38 UTC
Labels: bug, good first issue, admin-ui
