### ISSUE TITLE
Tenant creation fails

### ISSUE THREAD

**Issue by kohken-s** [awslabs/aws-saas-boost#453] opened 2022-12-30 08:55 UTC
Hi, Team

Tenant creation fails

AWS SaaS Boost Version :1.1.1, 2.0.0, 2.0.1, 2.1.0, 2.1.0-2
i tried different versions

2.0.0 later case 
Installed SaaS Boost successfully.
after install do the following
1. IAM onboarding-svc-role add ECRFullAccess  
      because ECR Repositories not Created
2. IAM workload-deploy-role add ECSFullAccess
      because ECS Claster not Created

Login to AWS SaaS boost, Create and provide Application Details.
Upload appliation image to AWS ECR Repository.
Provisioning tenant --> Failed

ECS console check 
Task not created  ----  Deploy Error --- Tenant creation fails
CloudWatch check workload-deploy log
 INFO  EcsDeploy - No active, provisioned tenants to deploy to 0

is there anything i can do

sorry, i can't write english well

### Environment

  - **AWS Region  :us-west-2
  - **AWS SaaS Boost Version :2.1.0-2 
  - **Workload OS  (Linux or Windows) :Linux

This is :bug: Bug Report
![WS000003](https://user-images.githubusercontent.com/75592708/210052230-6305e68d-fdd8-4c55-8a10-7d7fc1a509e9.JPG)

**Comment by kohken-s** [comment] 2022-12-31 08:53
1, use the updated version of the efs-utils package.
2. SaasBoost 2.1.0-2 installed
3. Login to AWS SaaS boost, Create and provide Application Details.
4. Upload appliation image to AWS ECR Repository.
5. Provisioning tenant --> Failed

![WS000004](https://user-images.githubusercontent.com/75592708/210130854-38648378-e713-4189-927f-38f1ac58016d.JPG)

[onboarding-events] error log

please advice

**Comment by raman231** [comment] 2023-01-02 13:51
This one has the same root cause as Issue #452

**Comment by raman231** [comment] 2023-01-02 13:52
Pull Request #454 already in place with the fix for this. Waiting review and merge to main

**Comment by PoeppingT** [comment] 2023-01-03 18:20
Thanks for your detailed investigation @kohken-s . Closing this issue as a duplicate of https://github.com/awslabs/aws-saas-boost/issues/452

**Comment by kohken-s** [comment] 2023-01-05 01:18
Hi, Team

Thank you update.

2.1.0-6 installed.
But Install Error

Installation Error: Error with CloudFormation stack sb-*****. Check the events in the AWS CloudFormation Console
CloudFormation:  InvokeRdsOptions - Custom::CustomResource - CREATE_FAILED

Can not Login to AWS SaaS boost Console
where is the problem. please advice.

![WS000006](https://user-images.githubusercontent.com/75592708/210677346-eab54155-4304-47df-973f-240eacc1413c.JPG)

**Comment by brtrvn** [comment] 2023-01-05 20:23
Resolved with the merge of #460

**Closed by brtrvn** 2023-01-05 20:23 UTC
Labels: bug, triage
