### ISSUE TITLE
Onboarding Check if Quotas  Fargate On-Demand resource count

### ISSUE THREAD

**Issue by kaveerh** [awslabs/aws-saas-boost#408] opened 2022-11-03 07:46 UTC
Quota will be exceeded for service Fargate On-Demand resource count. You are currently consuming 1.0, and Service Quota is 0.0.
###
fargate had move to vcpu base quote checking the resource quota for new account is not valid 
https://aws.amazon.com/blogs/containers/migrating-fargate-service-quotas-to-vcpu-based-quotas/

####
OnboardingService.java
  if (!passed) {
    LOGGER.error("Provisioning will exceed limits. {}", quotaMessage);
    failOnboarding(onboardingId, "Provisioning will exceed limits " + quotaMessage);
    fatal.add(message);
       continue;

**Comment by brtrvn** [comment] 2022-11-03 15:25
@kaveerh What version are you running? What region? If you go to the Service Quotas console page in your AWS account, what do you see for AWS Fargate?
https://console.aws.amazon.com/servicequotas/home/services/fargate/quotas

We merged a fix for the new vCPU quotas about a week ago
https://github.com/awslabs/aws-saas-boost/pull/390

**Comment by brtrvn** [comment] 2022-11-04 16:32
Duplicate of #388

**Closed by brtrvn** 2022-11-04 16:32 UTC
Labels: blocked
